### PR TITLE
Add Question Feature (admin)

### PR DESCRIPTION
**Pull request by girimohan**
Hello
I have added code for add question feature for admin. Please review and approve it.
Regards,
Mohan Giri

### CODE REVIEW

**Review by DGautam11 — CHANGES_REQUESTED** [review]
Hello Mohan,
I looked at your code you did the form submit by get method. Please update it using post method. Please update your add question link so that It will redirect the user to form page using servlet controller.
Regards,
Deepan Gautam

**Review by KharelSuraj — CHANGES_REQUESTED** [review]
Hello Mohan, 
Your form is done in get method. Please submit using the post method. 
Kind Regards, 
Suraj Kharel

**Comment by girimohan** [comment]
Hello
I have updated the code using post method. Please have a look and review it.
Regards,
Mohan

**Review by DGautam11 — APPROVED** [review]
Hello Mohan,
I looked at your code. It looks fine. You can go ahead and merge it to the main branch,
Regards,
Deepan Gautam

**Review by KharelSuraj — APPROVED** [review]
Hello Mohan, 
You can merge it now. 

Best Regards, 
Suraj Kharel

**Pull request merged**
